import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import { getBranchStock, transferBranchStock } from "../lib/branchStock";

type Branch={id:string;name:string};
type Product={id:number;label:string};
type Transfer={id:string;transfer_number:string;status:string;notes:string;requested_at:string;from_branch_id:string;to_branch_id:string};

export default function AdvancedOperations(){
 const [branches,setBranches]=useState<Branch[]>([]),[products,setProducts]=useState<Product[]>([]),[transfers,setTransfers]=useState<Transfer[]>([]),[fromBranch,setFromBranch]=useState(""),[toBranch,setToBranch]=useState(""),[productId,setProductId]=useState(""),[quantity,setQuantity]=useState("1"),[notes,setNotes]=useState(""),[available,setAvailable]=useState(0),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 useEffect(()=>{void load()},[]);useEffect(()=>{void loadAvailable()},[fromBranch,productId]);
 async function load(){setLoading(true);const [b,p,t]=await Promise.all([supabase.from("branches").select("id,name").eq("is_active",true).order("name"),supabase.from("product_details").select("id,name,products(name)").order("name").limit(1000),supabase.from("stock_transfers").select("id,transfer_number,status,notes,requested_at,from_branch_id,to_branch_id").order("requested_at",{ascending:false}).limit(100)]);if(b.error)alert(b.error.message);if(p.error)alert(p.error.message);if(t.error)alert(t.error.message);setBranches((b.data||[]) as Branch[]);setProducts((p.data||[]).map((x:any)=>({id:Number(x.id),label:`${Array.isArray(x.products)?x.products[0]?.name:x.products?.name||"منتج"} — ${x.name}`})));setTransfers((t.data||[]) as Transfer[]);setLoading(false)}
 async function loadAvailable(){if(!fromBranch||!productId){setAvailable(0);return}try{const rows=await getBranchStock(fromBranch);setAvailable(rows.find(x=>x.productDetailId===Number(productId))?.stock||0)}catch{setAvailable(0)}}
 async function submit(){const q=Number(quantity);if(!fromBranch||!toBranch||!productId||q<=0)return alert("اختار الفرعين والمنتج والكمية");if(fromBranch===toBranch)return alert("الفرع المرسل والمستلم لازم يكونوا مختلفين");if(q>available)return alert(`الكمية أكبر من المتاح في الفرع المرسل. المتاح: ${available}`);if(!confirm(`تأكيد نقل ${q} من ${name(fromBranch)} إلى ${name(toBranch)}؟`))return;setSaving(true);try{await transferBranchStock({fromBranchId:fromBranch,toBranchId:toBranch,productDetailId:Number(productId),quantity:q,notes});setQuantity("1");setNotes("");await Promise.all([load(),loadAvailable()]);alert("تم نقل المخزون بنجاح ✅")}catch(e){alert(e instanceof Error?e.message:"تعذر نقل المخزون")}finally{setSaving(false)}}
 const branchMap=useMemo(()=>new Map(branches.map(x=>[x.id,x.name])),[branches]);const name=(id:string)=>branchMap.get(id)||"—";
 if(loading)return <div dir="rtl" className="p-8 font-bold">جاري التحميل...</div>;
 return <div dir="rtl" className="space-y-6 p-4 md:p-8"><header><h1 className="text-3xl font-black">نقل المخزون بين الفروع</h1><p className="mt-2 text-gray-500">النقل يتم لحظيًا وبمعاملة واحدة: خصم من الفرع المرسل وإضافة للمستلم مع سجل حركة.</p></header><section className="grid gap-3 rounded-2xl bg-white p-5 shadow md:grid-cols-2 xl:grid-cols-5"><Select label="من فرع" value={fromBranch} set={setFromBranch} options={branches.map(x=>[x.id,x.name])}/><Select label="إلى فرع" value={toBranch} set={setToBranch} options={branches.map(x=>[x.id,x.name])}/><Select label="المنتج" value={productId} set={setProductId} options={products.map(x=>[String(x.id),x.label])}/><label className="text-sm font-bold">الكمية<input type="number" min="0.01" step="0.01" className="mt-2 w-full rounded-xl border p-3" value={quantity} onChange={e=>setQuantity(e.target.value)}/><span className="mt-1 block text-xs text-gray-500">المتاح: {available}</span></label><button disabled={saving} onClick={()=>void submit()} className="self-end rounded-xl bg-emerald-700 p-3 font-bold text-white disabled:opacity-50">{saving?"جاري النقل...":"تنفيذ النقل"}</button><label className="md:col-span-2 xl:col-span-5 text-sm font-bold">ملاحظات<textarea className="mt-2 w-full rounded-xl border p-3" value={notes} onChange={e=>setNotes(e.target.value)}/></label></section><section className="overflow-x-auto rounded-2xl bg-white p-4 shadow"><table className="w-full min-w-[760px] text-right"><thead><tr className="border-b"><Th>الرقم</Th><Th>من</Th><Th>إلى</Th><Th>الحالة</Th><Th>التاريخ</Th><Th>ملاحظات</Th></tr></thead><tbody>{transfers.map(t=><tr key={t.id} className="border-b"><Td>{t.transfer_number||t.id.slice(0,8)}</Td><Td>{name(t.from_branch_id)}</Td><Td>{name(t.to_branch_id)}</Td><Td>{t.status==="completed"?"مكتمل":t.status}</Td><Td>{new Date(t.requested_at).toLocaleString("ar-LY")}</Td><Td>{t.notes||"—"}</Td></tr>)}</tbody></table></section></div>
}
function Select({label,value,set,options}:{label:string;value:string;set:(x:string)=>void;options:string[][]}){return <label className="text-sm font-bold">{label}<select className="mt-2 w-full rounded-xl border p-3" value={value} onChange={e=>set(e.target.value)}><option value="">اختار...</option>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Th({children}:{children:any}){return <th className="p-3">{children}</th>}function Td({children}:{children:any}){return <td className="p-3">{children}</td>}
