import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";

type Branch={id:string;name:string;code:string;address:string;latitude:number|null;longitude:number|null;gpsRadius:number;isActive:boolean};
const empty={name:"",code:"",address:"",latitude:"",longitude:"",gpsRadius:"150"};

export default function Branches(){
 const [rows,setRows]=useState<Branch[]>([]),[form,setForm]=useState(empty),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[editingId,setEditingId]=useState<string|null>(null);
 useEffect(()=>{void load()},[]);
 async function load(){setLoading(true);const {data,error}=await supabase.from("branches").select("id,name,code,address,latitude,longitude,gps_radius,is_active").order("name");if(error)alert(`خطأ الفروع: ${error.message}\nشغّل ملف SQL الجديد أولاً.`);else setRows((data||[]).map((x:any)=>({id:String(x.id),name:String(x.name||""),code:String(x.code||""),address:String(x.address||""),latitude:x.latitude==null?null:Number(x.latitude),longitude:x.longitude==null?null:Number(x.longitude),gpsRadius:Number(x.gps_radius||150),isActive:Boolean(x.is_active)})));setLoading(false)}
 function currentLocation(){if(!navigator.geolocation)return alert("الجهاز لا يدعم تحديد الموقع");navigator.geolocation.getCurrentPosition(p=>setForm({...form,latitude:String(p.coords.latitude),longitude:String(p.coords.longitude)}),e=>alert(`تعذر تحديد الموقع: ${e.message}`),{enableHighAccuracy:true,timeout:15000})}
 async function save(){if(!form.name.trim()||!form.code.trim())return alert("اكتب اسم الفرع ورمزه");setSaving(true);const payload={name:form.name.trim(),code:form.code.trim(),address:form.address.trim(),latitude:form.latitude?Number(form.latitude):null,longitude:form.longitude?Number(form.longitude):null,gps_radius:Number(form.gpsRadius||150),is_active:true};const q=editingId?supabase.from("branches").update(payload).eq("id",editingId):supabase.from("branches").insert(payload);const {error}=await q;setSaving(false);if(error)return alert(error.message);setForm(empty);setEditingId(null);void load()}
 function edit(r:Branch){setEditingId(r.id);setForm({name:r.name,code:r.code,address:r.address,latitude:r.latitude==null?"":String(r.latitude),longitude:r.longitude==null?"":String(r.longitude),gpsRadius:String(r.gpsRadius)});window.scrollTo({top:0,behavior:"smooth"})}
 async function toggle(r:Branch){await supabase.from("branches").update({is_active:!r.isActive}).eq("id",r.id);void load()}
 return <div dir="rtl" className="space-y-6 p-4 md:p-8"><header><h1 className="text-3xl font-black">إدارة الفروع</h1><p className="mt-2 text-gray-500">أضف الفرع الثاني وحدد موقعه ونطاق GPS للحضور.</p></header><section className="grid gap-3 rounded-2xl bg-white p-5 shadow md:grid-cols-2 xl:grid-cols-3">{Object.entries({name:"اسم الفرع",code:"رمز الفرع",address:"العنوان",latitude:"خط العرض",longitude:"خط الطول",gpsRadius:"نطاق GPS بالمتر"}).map(([k,l])=><label key={k} className="text-sm font-bold">{l}<input className="mt-2 w-full rounded-xl border p-3" value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<button onClick={currentLocation} className="rounded-xl bg-blue-50 p-3 font-bold text-blue-700">📍 تحديد موقعي الحالي</button><button onClick={()=>void save()} disabled={saving} className="rounded-xl bg-emerald-700 p-3 font-bold text-white">{saving?"جاري الحفظ...":editingId?"حفظ التعديل":"إضافة الفرع"}</button>{editingId&&<button onClick={()=>{setEditingId(null);setForm(empty)}} className="rounded-xl bg-gray-100 p-3 font-bold">إلغاء التعديل</button>}</section>{loading?<p>جاري التحميل...</p>:<div className="grid gap-4 md:grid-cols-2">{rows.map(r=><div key={r.id} className="rounded-2xl bg-white p-5 shadow"><div className="flex items-start justify-between"><div><h2 className="text-xl font-black">{r.name}</h2><p className="text-gray-500">{r.code} — {r.address||"بدون عنوان"}</p></div><span className={`rounded-full px-3 py-1 text-sm font-bold ${r.isActive?"bg-emerald-100 text-emerald-700":"bg-gray-100"}`}>{r.isActive?"نشط":"موقوف"}</span></div><p className="mt-4 text-sm">GPS: {r.latitude??"—"}, {r.longitude??"—"} — النطاق {r.gpsRadius}م</p><div className="mt-4 flex gap-2"><button onClick={()=>edit(r)} className="rounded-xl bg-blue-50 px-4 py-2 font-bold text-blue-700">تعديل</button><button onClick={()=>void toggle(r)} className="rounded-xl bg-gray-100 px-4 py-2 font-bold">{r.isActive?"إيقاف":"تفعيل"}</button></div></div>)}</div>}</div>}
