import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import { useBranch } from "../context/BranchContext";

type Driver={id:string;name:string;phone:string;companyName:string;notes:string;isActive:boolean};
export default function Drivers(){
  const {effectiveBranchId}=useBranch();
  const [rows,setRows]=useState<Driver[]>([]),[search,setSearch]=useState(""),[name,setName]=useState(""),[phone,setPhone]=useState(""),[company,setCompany]=useState(""),[notes,setNotes]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{void load()},[effectiveBranchId]);
  async function load(){let q=supabase.from("delivery_drivers").select("id,name,phone,company_name,notes,is_active").order("name");if(effectiveBranchId)q=q.eq("branch_id",effectiveBranchId);const {data,error}=await q;if(error)return alert(error.message);setRows((data||[]).map((x:any)=>({id:String(x.id),name:String(x.name),phone:String(x.phone||""),companyName:String(x.company_name||""),notes:String(x.notes||""),isActive:Boolean(x.is_active)})))}
  async function add(){if(!effectiveBranchId)return alert("اختر فرعًا محددًا");if(!name.trim())return alert("اكتب اسم المندوب");setBusy(true);const {error}=await supabase.from("delivery_drivers").insert({branch_id:effectiveBranchId,name:name.trim(),phone:phone.trim()||null,company_name:company.trim()||null,notes:notes.trim()||null});setBusy(false);if(error)return alert(error.message);setName("");setPhone("");setCompany("");setNotes("");void load()}
  async function toggle(row:Driver){const {error}=await supabase.from("delivery_drivers").update({is_active:!row.isActive}).eq("id",row.id);if(error)return alert(error.message);void load()}
  const filtered=useMemo(()=>rows.filter(x=>`${x.name} ${x.phone} ${x.companyName}`.toLowerCase().includes(search.toLowerCase())),[rows,search]);
  return <div dir="rtl" className="space-y-5 p-3 sm:p-6 lg:p-8"><header><h1 className="text-2xl font-black sm:text-3xl">مندوبو التوصيل</h1><p className="mt-1 text-sm text-gray-500">قائمة مستقلة تظهر تلقائيًا عند كتابة اسم الكابتن داخل الطلب.</p></header><section className="rounded-2xl bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><input className="rounded-xl border p-3" placeholder="اسم المندوب" value={name} onChange={e=>setName(e.target.value)}/><input className="rounded-xl border p-3" placeholder="رقم الهاتف" value={phone} onChange={e=>setPhone(e.target.value)}/><input className="rounded-xl border p-3" placeholder="الشركة" value={company} onChange={e=>setCompany(e.target.value)}/><input className="rounded-xl border p-3" placeholder="ملاحظات" value={notes} onChange={e=>setNotes(e.target.value)}/></div><button disabled={busy} onClick={()=>void add()} className="mt-3 w-full rounded-xl bg-emerald-700 p-3 font-bold text-white sm:w-auto">{busy?"جاري الحفظ...":"إضافة مندوب"}</button></section><section className="rounded-2xl bg-white p-4 shadow-sm"><input className="mb-4 w-full rounded-xl border p-3" placeholder="بحث..." value={search} onChange={e=>setSearch(e.target.value)}/><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filtered.map(x=><article key={x.id} className="rounded-2xl border p-4"><div className="flex items-start justify-between"><div><h3 className="font-black">{x.name}</h3><p className="text-sm text-gray-500">{x.phone||"بدون رقم"}</p><p className="text-sm text-gray-500">{x.companyName||"بدون شركة"}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${x.isActive?"bg-green-100 text-green-700":"bg-gray-100 text-gray-600"}`}>{x.isActive?"نشط":"موقوف"}</span></div><button onClick={()=>void toggle(x)} className="mt-3 rounded-lg bg-gray-100 px-3 py-2 text-sm font-bold">تغيير الحالة</button></article>)}</div></section></div>
}
