import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import { useBranch } from "../context/BranchContext";
import { getBranchStock } from "../lib/branchStock";

type Material={id:number;name:string;price:number;stock:number};
type Component={productDetailId:number;name:string;quantity:number;unitPrice:number};
type Offer={id:number;title:string;offerType:string;offerPrice:number;startsAt:string;endsAt:string|null;isActive:boolean;components:Component[]};
const today=()=>new Date().toISOString().slice(0,10);
export default function Offers(){const {effectiveBranchId}=useBranch();const [materials,setMaterials]=useState<Material[]>([]),[offers,setOffers]=useState<Offer[]>([]),[offerType,setOfferType]=useState("bouquet"),[title,setTitle]=useState(""),[price,setPrice]=useState(""),[startsAt,setStartsAt]=useState(today()),[endsAt,setEndsAt]=useState(""),[components,setComponents]=useState<Component[]>([]),[selected,setSelected]=useState(""),[qty,setQty]=useState("1"),[busy,setBusy]=useState(false);useEffect(()=>{void load()},[effectiveBranchId]);async function load(){const [p,d,o,stock]=await Promise.all([supabase.from("products").select("id,name"),supabase.from("product_details").select("id,product_id,name,color,sell_price,unit_sell_price"),supabase.from("offers").select("id,title,offer_type,offer_price,starts_at,ends_at,is_active,components,branch_id").order("created_at",{ascending:false}),getBranchStock(effectiveBranchId)]);if(p.error||d.error||o.error)return alert(p.error?.message||d.error?.message||o.error?.message||"خطأ");const pm=new Map((p.data||[]).map((x:any)=>[Number(x.id),String(x.name)]));const sm=new Map(stock.map(x=>[x.productDetailId,x.stock]));setMaterials((d.data||[]).map((x:any)=>({id:Number(x.id),name:`${pm.get(Number(x.product_id))||"منتج"} — ${x.color||x.name||"خيار"}`,price:Number(x.unit_sell_price||x.sell_price||0),stock:Number(sm.get(Number(x.id))||0)})));const scoped=effectiveBranchId?(o.data||[]).filter((x:any)=>String(x.branch_id||"")===effectiveBranchId):(o.data||[]);setOffers(scoped.map((x:any)=>({id:Number(x.id),title:String(x.title||"عرض"),offerType:String(x.offer_type||"product"),offerPrice:Number(x.offer_price||0),startsAt:String(x.starts_at||"").slice(0,10),endsAt:x.ends_at?String(x.ends_at).slice(0,10):null,isActive:Boolean(x.is_active),components:Array.isArray(x.components)?x.components:[]})))}
const selectedMaterial=useMemo(()=>materials.find(x=>x.id===Number(selected)),[materials,selected]);function addComponent(){if(!selectedMaterial)return alert("اختر مكوّنًا");const quantity=Math.max(1,Number(qty||1));setComponents(prev=>{const found=prev.find(x=>x.productDetailId===selectedMaterial.id);return found?prev.map(x=>x.productDetailId===selectedMaterial.id?{...x,quantity:x.quantity+quantity}:x):[...prev,{productDetailId:selectedMaterial.id,name:selectedMaterial.name,quantity,unitPrice:selectedMaterial.price}]});setSelected("");setQty("1")}
async function save(){if(!effectiveBranchId)return alert("اختر فرعًا محددًا");if(!title.trim())return alert("اكتب اسم العرض");if(!(Number(price)>0))return alert("اكتب سعر العرض");if(components.length===0)return alert("أضف مكوّنًا واحدًا على الأقل");setBusy(true);const first=components[0];const original=components.reduce((s,x)=>s+x.quantity*x.unitPrice,0);const {error}=await supabase.from("offers").insert({branch_id:effectiveBranchId,title:title.trim(),offer_type:offerType,product_detail_id:offerType==="product"?first.productDetailId:null,original_price:original,offer_price:Number(price),starts_at:startsAt,ends_at:endsAt||null,is_active:true,components});setBusy(false);if(error)return alert(error.message);setTitle("");setPrice("");setComponents([]);void load()}
async function toggle(o:Offer){const {error}=await supabase.from("offers").update({is_active:!o.isActive}).eq("id",o.id);if(error)return alert(error.message);void load()}
return <div dir="rtl" className="space-y-5 p-3 sm:p-6 lg:p-8"><header><h1 className="text-2xl font-black sm:text-3xl">العروض</h1><p className="mt-1 text-sm text-gray-500">أنشئ العرض مثل الطلب: باقة أو بوكس أو منتج، ثم أضف مكوناته وسعره.</p></header><section className="rounded-2xl bg-white p-4 shadow-sm"><div className="grid grid-cols-3 gap-2">{[["bouquet","باقة"],["box","بوكس"],["product","منتج"]].map(([k,l])=><button key={k} onClick={()=>setOfferType(k)} className={`rounded-xl p-3 font-bold ${offerType===k?"bg-emerald-700 text-white":"bg-gray-100"}`}>{l}</button>)}</div><div className="mt-4 grid gap-3 md:grid-cols-2"><input className="rounded-xl border p-3" placeholder="اسم العرض" value={title} onChange={e=>setTitle(e.target.value)}/><input type="number" className="rounded-xl border p-3" placeholder="سعر العرض" value={price} onChange={e=>setPrice(e.target.value)}/><input type="date" className="rounded-xl border p-3" value={startsAt} onChange={e=>setStartsAt(e.target.value)}/><input type="date" className="rounded-xl border p-3" value={endsAt} onChange={e=>setEndsAt(e.target.value)}/></div><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_120px_auto]"><select className="rounded-xl border p-3" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">اختر مكوّن العرض</option>{materials.map(x=><option key={x.id} value={x.id}>{x.name} | {x.price} د.ل | مخزون {x.stock}</option>)}</select><input type="number" min="1" className="rounded-xl border p-3" value={qty} onChange={e=>setQty(e.target.value)}/><button onClick={addComponent} className="rounded-xl bg-gray-900 px-5 font-bold text-white">إضافة</button></div><div className="mt-4 space-y-2">{components.map(x=><div key={x.productDetailId} className="flex items-center justify-between rounded-xl bg-gray-50 p-3"><span>{x.name} × {x.quantity}</span><button onClick={()=>setComponents(c=>c.filter(i=>i.productDetailId!==x.productDetailId))} className="text-red-700">حذف</button></div>)}</div><button disabled={busy} onClick={()=>void save()} className="mt-4 w-full rounded-xl bg-emerald-700 p-3 font-black text-white sm:w-auto">حفظ العرض</button></section><section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{offers.map(o=><article key={o.id} className="rounded-2xl bg-white p-4 shadow-sm"><div className="flex justify-between"><div><h3 className="font-black">{o.title}</h3><p className="text-sm text-gray-500">{o.offerType==="bouquet"?"باقة":o.offerType==="box"?"بوكس":"منتج"} — {o.components.length} مكوّن</p></div><strong className="text-emerald-700">{o.offerPrice.toFixed(2)} د.ل</strong></div><button onClick={()=>void toggle(o)} className={`mt-3 rounded-lg px-3 py-2 text-sm font-bold ${o.isActive?"bg-red-50 text-red-700":"bg-green-50 text-green-700"}`}>{o.isActive?"إيقاف العرض":"تفعيل العرض"}</button></article>)}</section></div>}
