import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import { useBranch } from "../context/BranchContext";

type ProductOption={id:number;label:string;stock:number};
export default function OpeningStock(){
 const {effectiveBranchId}=useBranch();
 const [products,setProducts]=useState<ProductOption[]>([]); const [productId,setProductId]=useState(""); const [qty,setQty]=useState(""); const [cost,setCost]=useState(""); const [sell,setSell]=useState(""); const [date,setDate]=useState(new Date().toISOString().slice(0,10)); const [notes,setNotes]=useState("مخزون قبل تشغيل المنظومة"); const [busy,setBusy]=useState(false);
 useEffect(()=>{void load()},[effectiveBranchId]);
 async function load(){if(!effectiveBranchId){setProducts([]);return;} const {data,error}=await supabase.from("product_details").select("id,name,stock,products(name)").order("id"); if(error)return alert(error.message); setProducts((data||[]).map((x:any)=>({id:Number(x.id),label:[Array.isArray(x.products)?x.products[0]?.name:x.products?.name,x.name].filter(Boolean).join(" - "),stock:Number(x.stock||0)})))}
 async function save(){if(!effectiveBranchId)return alert("اختر فرعًا محددًا"); const q=Number(qty),c=Number(cost),p=Number(sell); if(!productId||q<=0)return alert("اختر المنتج واكتب الكمية"); setBusy(true); const {error}=await supabase.rpc("add_opening_stock",{p_branch_id:effectiveBranchId,p_product_detail_id:Number(productId),p_quantity:q,p_unit_cost:Math.max(c,0),p_sell_price:Math.max(p,0),p_opening_date:date,p_notes:notes.trim()}); setBusy(false); if(error)return alert(error.message); alert("تمت إضافة الرصيد الافتتاحي بدون تسجيله كمشتريات اليوم ✅"); setProductId("");setQty("");setCost("");setSell("");}
 return <div dir="rtl" className="space-y-6 p-4 md:p-8"><header><h1 className="text-3xl font-black">الرصيد الافتتاحي للمخزون</h1><p className="mt-1 text-gray-500">لإدخال البضاعة الموجودة قبل تشغيل المنظومة؛ تزيد المخزون ولا تنشئ فاتورة مشتريات أو دين مورد.</p></header><section className="rounded-2xl bg-white p-5 shadow"><div className="grid gap-4 md:grid-cols-2"><label>المنتج<select className="mt-1 w-full rounded-xl border p-3" value={productId} onChange={e=>setProductId(e.target.value)}><option value="">اختر المنتج</option>{products.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>الكمية الحالية<input type="number" className="mt-1 w-full rounded-xl border p-3" value={qty} onChange={e=>setQty(e.target.value)}/></label><label>تكلفة الوحدة الأصلية أو التقريبية<input type="number" className="mt-1 w-full rounded-xl border p-3" value={cost} onChange={e=>setCost(e.target.value)}/></label><label>سعر البيع الحالي<input type="number" className="mt-1 w-full rounded-xl border p-3" value={sell} onChange={e=>setSell(e.target.value)}/></label><label>تاريخ الرصيد<input type="date" className="mt-1 w-full rounded-xl border p-3" value={date} onChange={e=>setDate(e.target.value)}/></label><label>ملاحظات<input className="mt-1 w-full rounded-xl border p-3" value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><button disabled={busy} onClick={()=>void save()} className="mt-5 rounded-xl bg-emerald-700 px-6 py-3 font-bold text-white disabled:opacity-50">{busy?"جاري الحفظ...":"إضافة للمخزون كرصد افتتاحي"}</button></section></div>
}
