import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import { useBranch } from "../context/BranchContext";

type Tx={id:string;direction:"in"|"out";account:"cash"|"bank";amount:number;description:string;occurredAt:string;sourceType:string};
const input="w-full rounded-xl border border-gray-200 bg-white p-3 outline-none focus:border-emerald-600";
export default function Treasury(){
 const {effectiveBranchId}=useBranch();const [rows,setRows]=useState<Tx[]>([]),[loading,setLoading]=useState(true),[account,setAccount]=useState<"cash"|"bank">("cash"),[direction,setDirection]=useState<"in"|"out">("in"),[amount,setAmount]=useState(""),[note,setNote]=useState(""),[saving,setSaving]=useState(false);
 useEffect(()=>{void load()},[effectiveBranchId]);
 async function load(){setLoading(true);try{let q=supabase.from("financial_transactions").select("id,direction,account,amount,description,occurred_at,source_type").order("occurred_at",{ascending:false});if(effectiveBranchId)q=q.eq("branch_id",effectiveBranchId);const {data,error}=await q;if(error)throw error;setRows((data||[]).map((x:any)=>({id:String(x.id),direction:x.direction,account:x.account,amount:Number(x.amount||0),description:String(x.description||""),occurredAt:String(x.occurred_at||""),sourceType:String(x.source_type||"")})))}catch(e){alert(e instanceof Error?e.message:"تعذر تحميل الرصيد")}finally{setLoading(false)}}
 const totals=useMemo(()=>{let cash=0,bank=0;for(const x of rows){const sign=x.direction==="in"?1:-1;if(x.account==="cash")cash+=sign*x.amount;else bank+=sign*x.amount}return{cash,bank,total:cash+bank}},[rows]);
 async function addManual(){if(!effectiveBranchId)return alert("اختر فرعًا محددًا");const v=Number(amount);if(!(v>0))return alert("اكتب مبلغ صحيح");if(!note.trim())return alert("اكتب سبب الحركة");setSaving(true);try{const {error}=await supabase.from("financial_transactions").insert({branch_id:effectiveBranchId,source_type:"manual",source_id:crypto.randomUUID(),direction,account,amount:v,description:note.trim(),occurred_at:new Date().toISOString()});if(error)throw error;setAmount("");setNote("");await load()}catch(e){alert(e instanceof Error?e.message:"تعذر حفظ الحركة")}finally{setSaving(false)}}
 const Card=({label,value}:{label:string;value:number})=><div className="rounded-2xl bg-white p-6 shadow"><p className="text-gray-500">{label}</p><p className={`mt-2 text-3xl font-black ${value<0?"text-red-700":"text-emerald-800"}`}>{value.toFixed(2)} د.ل</p></div>;
 return <div dir="rtl" className="space-y-6 p-4 md:p-8"><header><h1 className="text-3xl font-black">💵 الرصيد الحالي</h1><p className="mt-2 text-gray-500">مصدر واحد للحقيقة: أي بيع أو شراء أو مصروف أو دفعة مسجلة تحرك الكاش أو المصرف تلقائيًا.</p></header>{loading?<div>جاري التحميل...</div>:<><div className="grid gap-4 md:grid-cols-3"><Card label="الكاش الحالي" value={totals.cash}/><Card label="المصرف الحالي" value={totals.bank}/><Card label="الإجمالي" value={totals.total}/></div><section className="rounded-2xl bg-white p-5 shadow"><h2 className="text-xl font-black">حركة يدوية / تصحيح رصيد</h2><p className="mt-1 text-sm text-gray-500">للإيداع أو السحب الذي لا يمر بفاتورة أو طلب.</p><div className="mt-4 grid gap-3 md:grid-cols-4"><select className={input} value={account} onChange={e=>setAccount(e.target.value as any)}><option value="cash">كاش</option><option value="bank">مصرف</option></select><select className={input} value={direction} onChange={e=>setDirection(e.target.value as any)}><option value="in">إيداع / داخل</option><option value="out">سحب / خارج</option></select><input type="number" className={input} value={amount} onChange={e=>setAmount(e.target.value)} placeholder="المبلغ"/><input className={input} value={note} onChange={e=>setNote(e.target.value)} placeholder="السبب"/></div><button disabled={saving} onClick={()=>void addManual()} className="mt-3 rounded-xl bg-gray-900 px-6 py-3 font-black text-white">حفظ الحركة</button></section><section className="overflow-x-auto rounded-2xl bg-white p-5 shadow"><h2 className="mb-4 text-xl font-black">آخر الحركات</h2><table className="w-full min-w-[760px]"><thead className="bg-gray-50"><tr><Th>الوقت</Th><Th>البيان</Th><Th>الحساب</Th><Th>الحركة</Th><Th>المبلغ</Th></tr></thead><tbody>{rows.slice(0,100).map(x=><tr key={x.id} className="border-b"><Td>{new Date(x.occurredAt).toLocaleString("ar-LY")}</Td><Td>{x.description}</Td><Td>{x.account==="cash"?"كاش":"مصرف"}</Td><Td><span className={x.direction==="in"?"font-bold text-emerald-700":"font-bold text-red-700"}>{x.direction==="in"?"داخل":"خارج"}</span></Td><Td>{x.amount.toFixed(2)} د.ل</Td></tr>)}</tbody></table></section></>}</div>}
function Th({children}:{children:React.ReactNode}){return <th className="p-3 text-right">{children}</th>}function Td({children}:{children:React.ReactNode}){return <td className="p-3">{children}</td>}
