import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import { useBranch } from "../context/BranchContext";

type Totals={cash:number;bank:number;balance:number;total:number};
export default function Treasury(){
 const {effectiveBranchId}=useBranch(); const [totals,setTotals]=useState<Totals>({cash:0,bank:0,balance:0,total:0}); const [loading,setLoading]=useState(true);
 useEffect(()=>{void load()},[effectiveBranchId]);
 async function load(){setLoading(true); let oq=supabase.from("orders").select("cash_amount,bank_amount,transfer_amount,balance_amount,deposit_amount,deposit_method,status,branch_id").neq("status","cancelled"); let eq=supabase.from("expenses").select("amount,payment_method,branch_id"); if(effectiveBranchId){oq=oq.eq("branch_id",effectiveBranchId);eq=eq.eq("branch_id",effectiveBranchId)} const [or,er]=await Promise.all([oq,eq]); let cash=0,bank=0,balance=0; for(const o of or.data||[]){cash+=Number((o as any).cash_amount||0);bank+=Number((o as any).bank_amount||0)+Number((o as any).transfer_amount||0);balance+=Number((o as any).balance_amount||0);const dep=Number((o as any).deposit_amount||0);if((o as any).deposit_method==="bank")bank+=dep;else if((o as any).deposit_method==="balance")balance+=dep;else cash+=dep} for(const e of er.data||[]){const a=Number((e as any).amount||0),m=String((e as any).payment_method||"cash");if(m.includes("bank")||m.includes("transfer")||m.includes("مصرف"))bank-=a;else if(m.includes("balance")||m.includes("رصيد"))balance-=a;else cash-=a} setTotals({cash:Math.round(cash),bank:Math.round(bank),balance:Math.round(balance),total:Math.round(cash+bank+balance)});setLoading(false)}
 const Card=({label,value}:{label:string,value:number})=><div className="rounded-2xl bg-white p-6 shadow"><p className="text-gray-500">{label}</p><p className="mt-2 text-3xl font-black">{value.toLocaleString("ar-LY")} د.ل</p></div>;
 return <div dir="rtl" className="space-y-6 p-4 md:p-8"><header><h1 className="text-3xl font-black">الخزينة والأرصدة</h1><p className="mt-2 text-gray-500">الرصيد المتوقع حسب حركات الطلبات والمصروفات للفرع المختار.</p></header>{loading?<div>جاري التحميل...</div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Card label="الكاش المتوقع" value={totals.cash}/><Card label="المصرف المتوقع" value={totals.bank}/><Card label="الرصيد" value={totals.balance}/><Card label="الإجمالي" value={totals.total}/></div>}<p className="rounded-xl bg-amber-50 p-4 text-sm text-amber-800">هذه أرقام محاسبية متوقعة من البيانات المسجلة. يلزم إدخال كل سحب أو إيداع كمصروف أو حركة مالية حتى تطابق الواقع.</p></div>;
}