-- MOOD 2026-07-25: tasks, safer settings/suppliers, item tracking, expenses classification, web push
create extension if not exists pgcrypto;

-- Settings tables/columns required by the current UI
create table if not exists public.app_settings (
  id bigint generated by default as identity primary key,
  shop_name text not null default 'MOOD', phone text default '', address text default '', currency text default 'د.ل',
  logo_url text default '', whatsapp text default '', invoice_title text default 'فاتورة مبيعات', invoice_footer text default '',
  invoice_prefix text default 'INV', invoice_show_logo boolean default true, invoice_show_address boolean default true,
  invoice_show_phone boolean default true, invoice_show_customer_phone boolean default true, invoice_show_notes boolean default true,
  invoice_show_payment_method boolean default true, invoice_paper_size text default 'A6', invoice_orientation text default 'portrait',
  printer_name text default '', print_copies integer default 1, auto_print_customer_invoice boolean default false,
  auto_print_production_invoice boolean default false, show_print_preview boolean default true,
  payment_cash_enabled boolean default true, payment_card_enabled boolean default true, payment_transfer_enabled boolean default true,
  payment_deposit_enabled boolean default true, payment_mixed_enabled boolean default true,
  bank_name text default '', bank_account_name text default '', bank_account_number text default '', bank_iban text default '', bank_notes text default '',
  delivery_enabled boolean default true, default_delivery_fee numeric default 0, free_delivery_limit numeric default 0,
  delivery_note text default '', require_delivery_address boolean default true, require_delivery_phone boolean default true,
  backup_enabled boolean default true, backup_reminder_days integer default 7, last_backup_at timestamptz null,
  system_version text default '1.0.0', system_name text default 'MOOD Management System', updated_at timestamptz default now()
);
insert into public.app_settings(id) values (1) on conflict (id) do nothing;
alter table public.app_settings enable row level security;
drop policy if exists "settings authenticated all" on public.app_settings;
create policy "settings authenticated all" on public.app_settings for all to authenticated using (true) with check (true);

create table if not exists public.bouquet_sizes (
 id uuid primary key default gen_random_uuid(), name text not null, price numeric not null default 0,
 wrapping_count numeric not null default 0, ribbon_count numeric not null default 0, card_count numeric not null default 0,
 base_count numeric not null default 0, min_flowers integer not null default 1, max_flowers integer null,
 is_active boolean not null default true, created_at timestamptz default now()
);
create table if not exists public.box_variants (
 id uuid primary key default gen_random_uuid(), product_detail_id bigint null references public.product_details(id) on delete set null,
 box_type text not null, size text not null, price numeric not null default 0, flowers_count numeric not null default 0,
 accessories_count numeric not null default 0, wrapping_count numeric not null default 0, ribbon_count numeric not null default 0,
 card_count numeric not null default 0, is_active boolean not null default true, created_at timestamptz default now()
);
alter table public.bouquet_sizes enable row level security;
alter table public.box_variants enable row level security;
drop policy if exists "bouquet settings all" on public.bouquet_sizes;
create policy "bouquet settings all" on public.bouquet_sizes for all to authenticated using (true) with check (true);
drop policy if exists "box settings all" on public.box_variants;
create policy "box settings all" on public.box_variants for all to authenticated using (true) with check (true);

-- Supplier compatibility
alter table if exists public.suppliers add column if not exists phone text default '';
alter table if exists public.suppliers add column if not exists city text default '';
alter table if exists public.suppliers add column if not exists address text default '';
alter table if exists public.suppliers add column if not exists supplier_type text default 'عام';
alter table if exists public.suppliers add column if not exists notes text default '';
alter table if exists public.suppliers add column if not exists is_active boolean default true;
alter table if exists public.suppliers add column if not exists created_at timestamptz default now();
create table if not exists public.supplier_payments (
 id uuid primary key default gen_random_uuid(), supplier_id uuid not null references public.suppliers(id) on delete cascade,
 amount numeric not null check(amount > 0), payment_date date not null default current_date,
 payment_method text not null default 'cash', notes text default '', created_by uuid null references auth.users(id), created_at timestamptz default now()
);
alter table public.supplier_payments enable row level security;
drop policy if exists "supplier payments all" on public.supplier_payments;
create policy "supplier payments all" on public.supplier_payments for all to authenticated using (true) with check (true);

-- Tasks
create table if not exists public.tasks (
 id uuid primary key default gen_random_uuid(), title text not null, description text default '',
 assigned_to uuid null references auth.users(id) on delete set null, assigned_to_name text default '',
 priority text not null default 'normal' check(priority in ('normal','important','urgent')),
 status text not null default 'new' check(status in ('new','in_progress','completed','cancelled')),
 due_at timestamptz null, completed_at timestamptz null, completed_by uuid null references auth.users(id),
 created_by uuid null references auth.users(id), created_at timestamptz default now(), updated_at timestamptz default now()
);
create index if not exists tasks_status_due_idx on public.tasks(status,due_at);
alter table public.tasks enable row level security;
drop policy if exists "tasks authenticated all" on public.tasks;
create policy "tasks authenticated all" on public.tasks for all to authenticated using (true) with check (true);
do $$ begin alter publication supabase_realtime add table public.tasks; exception when duplicate_object then null; end $$;

-- Expenses: accounting classification and liability details
alter table if exists public.expenses add column if not exists accounting_type text default 'operating';
alter table if exists public.expenses add column if not exists liability_party text default '';
alter table if exists public.expenses add column if not exists due_date date null;
alter table if exists public.expenses add column if not exists paid_amount numeric default 0;
alter table if exists public.expenses add column if not exists liability_status text default 'unpaid';
update public.expenses set accounting_type = case when expense_type='fixed' then 'asset' else 'operating' end where accounting_type is null;

-- Push subscriptions
create table if not exists public.push_subscriptions (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
 endpoint text not null unique, p256dh text not null, auth text not null, user_agent text default '',
 is_active boolean not null default true, created_at timestamptz default now(), updated_at timestamptz default now()
);
alter table public.push_subscriptions enable row level security;
drop policy if exists "own push subscriptions" on public.push_subscriptions;
create policy "own push subscriptions" on public.push_subscriptions for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

-- Product movement ledger: future-safe unified history
create table if not exists public.inventory_movements (
 id uuid primary key default gen_random_uuid(), product_detail_id bigint null references public.product_details(id) on delete cascade,
 movement_type text not null, quantity numeric not null, balance_after numeric null, unit_cost numeric null, unit_price numeric null,
 reference_table text null, reference_id text null, supplier_id uuid null references public.suppliers(id) on delete set null,
 notes text default '', created_by uuid null references auth.users(id), created_at timestamptz default now()
);
create index if not exists inventory_movements_product_created_idx on public.inventory_movements(product_detail_id,created_at desc);
alter table public.inventory_movements enable row level security;
drop policy if exists "inventory movements authenticated" on public.inventory_movements;
create policy "inventory movements authenticated" on public.inventory_movements for all to authenticated using(true) with check(true);

-- Automatically record every stock change from now on.
create or replace function public.log_product_detail_stock_movement()
returns trigger language plpgsql security definer set search_path=public as $$
declare delta numeric;
begin
  delta := coalesce(new.stock,0) - coalesce(old.stock,0);
  if delta <> 0 then
    insert into public.inventory_movements(product_detail_id,movement_type,quantity,balance_after,unit_cost,unit_price,notes)
    values(new.id, case when delta>0 then 'purchase' else 'sale' end, delta, new.stock,
      coalesce(new.average_unit_cost,new.buy_price,0), coalesce(new.sell_price,new.unit_sell_price,0), 'حركة مخزون تلقائية');
  end if;
  return new;
end $$;
drop trigger if exists trg_product_detail_stock_movement on public.product_details;
create trigger trg_product_detail_stock_movement after update of stock on public.product_details
for each row execute function public.log_product_detail_stock_movement();

insert into public.inventory_movements(product_detail_id,movement_type,quantity,balance_after,unit_cost,unit_price,notes)
select pd.id,'opening',coalesce(pd.stock,0),coalesce(pd.stock,0),coalesce(pd.average_unit_cost,pd.buy_price,0),coalesce(pd.sell_price,pd.unit_sell_price,0),'رصيد افتتاحي عند تفعيل التتبع'
from public.product_details pd
where not exists(select 1 from public.inventory_movements im where im.product_detail_id=pd.id);
