begin;

-- مخزون منفصل لكل فرع
create table if not exists public.branch_inventory (
  id uuid primary key default gen_random_uuid(),
  branch_id uuid not null references public.branches(id) on delete cascade,
  product_detail_id bigint not null references public.product_details(id) on delete cascade,
  quantity numeric not null default 0,
  alert_limit numeric not null default 0,
  updated_at timestamptz not null default now(),
  unique(branch_id, product_detail_id)
);

create table if not exists public.stock_transfers (
  id uuid primary key default gen_random_uuid(),
  transfer_number text not null unique default ('TR-' || to_char(now(),'YYYYMMDDHH24MISS') || '-' || substr(gen_random_uuid()::text,1,4)),
  from_branch_id uuid not null references public.branches(id),
  to_branch_id uuid not null references public.branches(id),
  status text not null default 'pending' check (status in ('pending','approved','rejected','completed')),
  notes text not null default '',
  requested_by uuid null references public.user_profiles(id) on delete set null,
  approved_by uuid null references public.user_profiles(id) on delete set null,
  requested_at timestamptz not null default now(),
  approved_at timestamptz null,
  completed_at timestamptz null,
  check (from_branch_id <> to_branch_id)
);

create table if not exists public.stock_transfer_items (
  id uuid primary key default gen_random_uuid(),
  transfer_id uuid not null references public.stock_transfers(id) on delete cascade,
  product_detail_id bigint not null references public.product_details(id),
  quantity numeric not null check (quantity > 0)
);

-- الورديات والإجازات والأعذار
create table if not exists public.employee_shifts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.user_profiles(id) on delete cascade,
  branch_id uuid null references public.branches(id) on delete set null,
  weekday int not null check (weekday between 0 and 6),
  start_time time not null,
  end_time time not null,
  grace_minutes int not null default 10,
  is_active boolean not null default true,
  unique(user_id, weekday)
);

create table if not exists public.attendance_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.user_profiles(id) on delete cascade,
  request_type text not null check (request_type in ('excuse','leave','overtime','correction')),
  request_date date not null,
  from_time time null,
  to_time time null,
  reason text not null default '',
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  reviewed_by uuid null references public.user_profiles(id) on delete set null,
  reviewed_at timestamptz null,
  created_at timestamptz not null default now()
);

-- تطوير العملاء CRM والولاء
-- المنظومة القديمة كانت تحفظ بيانات العميل داخل جدول orders فقط، لذلك ننشئ جدول العملاء هنا
-- ثم ننقل إليه العملاء الحاليين ونبقيه متزامنًا تلقائيًا مع أي طلب جديد أو معدل.
create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null default '',
  phone text not null default '',
  birthday date null,
  anniversary date null,
  rating int not null default 0 check (rating between 0 and 5),
  notes text not null default '',
  loyalty_points numeric not null default 0,
  marketing_opt_in boolean not null default false,
  last_contact_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.customers add column if not exists birthday date null;
alter table public.customers add column if not exists anniversary date null;
alter table public.customers add column if not exists rating int not null default 0;
alter table public.customers add column if not exists notes text not null default '';
alter table public.customers add column if not exists loyalty_points numeric not null default 0;
alter table public.customers add column if not exists marketing_opt_in boolean not null default false;
alter table public.customers add column if not exists last_contact_at timestamptz null;
alter table public.customers add column if not exists created_at timestamptz not null default now();
alter table public.customers add column if not exists updated_at timestamptz not null default now();

create unique index if not exists customers_phone_unique_nonempty
  on public.customers(phone)
  where btrim(phone) <> '';

insert into public.customers(name, phone, last_contact_at)
select
  coalesce(nullif(btrim(o.customer_name), ''), 'عميل غير مسجل'),
  btrim(o.customer_phone),
  max(coalesce(o.created_at, now()))
from public.orders o
where btrim(coalesce(o.customer_phone, '')) <> ''
group by btrim(o.customer_phone), coalesce(nullif(btrim(o.customer_name), ''), 'عميل غير مسجل')
on conflict (phone) where btrim(phone) <> '' do update
set name = excluded.name,
    last_contact_at = greatest(public.customers.last_contact_at, excluded.last_contact_at),
    updated_at = now();

create or replace function public.sync_customer_from_order()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if btrim(coalesce(new.customer_phone, '')) <> '' then
    insert into public.customers(name, phone, last_contact_at, updated_at)
    values (
      coalesce(nullif(btrim(new.customer_name), ''), 'عميل غير مسجل'),
      btrim(new.customer_phone),
      coalesce(new.created_at, now()),
      now()
    )
    on conflict (phone) where btrim(phone) <> '' do update
    set name = excluded.name,
        last_contact_at = greatest(public.customers.last_contact_at, excluded.last_contact_at),
        updated_at = now();
  end if;
  return new;
end;
$$;

drop trigger if exists orders_sync_customer on public.orders;
create trigger orders_sync_customer
after insert or update of customer_name, customer_phone on public.orders
for each row execute function public.sync_customer_from_order();

create table if not exists public.customer_notes (
  id uuid primary key default gen_random_uuid(),
  customer_id bigint not null references public.customers(id) on delete cascade,
  note text not null,
  created_by uuid null references public.user_profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

-- تقييم المورد ومدة التوريد
alter table public.suppliers add column if not exists rating int not null default 0;
alter table public.suppliers add column if not exists average_delivery_days numeric not null default 0;
alter table public.suppliers add column if not exists notes text not null default '';
alter table public.suppliers add column if not exists is_active boolean not null default true;

create table if not exists public.supplier_price_history (
  id uuid primary key default gen_random_uuid(),
  supplier_id uuid not null references public.suppliers(id) on delete cascade,
  product_detail_id bigint not null references public.product_details(id) on delete cascade,
  buy_price numeric not null,
  recorded_at timestamptz not null default now()
);

-- إعدادات الملخص وعدم الإزعاج للمستخدم
alter table public.user_notification_preferences add column if not exists digest_mode text not null default 'instant' check (digest_mode in ('instant','daily','weekly'));
alter table public.user_notification_preferences add column if not exists dedupe_minutes int not null default 30;

-- صلاحيات إضافية
insert into public.app_permissions(code,name,group_name) values
('branches.transfer_stock','نقل المخزون بين الفروع','الفروع'),
('branches.approve_transfer','اعتماد نقل المخزون','الفروع'),
('attendance.manage_shifts','إدارة الورديات','الحضور'),
('attendance.manage_requests','إدارة الإجازات والأعذار','الحضور'),
('customers.crm','إدارة ملف العميل والولاء','العملاء'),
('suppliers.evaluate','تقييم الموردين ومقارنة الأسعار','الموردون'),
('reports.advanced','عرض التحليلات المتقدمة','التقارير')
on conflict (code) do update set name=excluded.name, group_name=excluded.group_name;

-- RLS مبسط متوافق مع بقية المشروع
alter table public.customers enable row level security;
alter table public.branch_inventory enable row level security;
alter table public.stock_transfers enable row level security;
alter table public.stock_transfer_items enable row level security;
alter table public.employee_shifts enable row level security;
alter table public.attendance_requests enable row level security;
alter table public.customer_notes enable row level security;
alter table public.supplier_price_history enable row level security;

do $$ declare t text; begin
  foreach t in array array['customers','branch_inventory','stock_transfers','stock_transfer_items','employee_shifts','attendance_requests','customer_notes','supplier_price_history'] loop
    execute format('drop policy if exists %I on public.%I', t || '_authenticated', t);
    execute format('create policy %I on public.%I for all to authenticated using (true) with check (true)', t || '_authenticated', t);
  end loop;
end $$;

commit;
