-- نظام مرتجعات الطلبات: تسجيل السبب، حالة كل عنصر، رد المبلغ، وإرجاع السليم فقط للمخزون.

create table if not exists public.order_returns (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete restrict,
  return_type text not null default 'full' check (return_type in ('full','partial')),
  reason text not null,
  notes text,
  refund_amount numeric(12,2) not null default 0,
  refund_method text not null default 'cash',
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.order_return_items (
  id bigint generated by default as identity primary key,
  return_id bigint not null references public.order_returns(id) on delete cascade,
  source_type text not null check (source_type in ('product_detail','usage_tier','external')),
  source_id text,
  item_name text not null,
  sold_quantity numeric(12,2) not null default 0,
  return_quantity numeric(12,2) not null check (return_quantity > 0),
  item_condition text not null check (item_condition in ('good','damaged')),
  restored_to_stock boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists order_returns_order_id_idx on public.order_returns(order_id);
create index if not exists order_return_items_return_id_idx on public.order_return_items(return_id);

alter table public.order_returns enable row level security;
alter table public.order_return_items enable row level security;

drop policy if exists "authenticated can read order returns" on public.order_returns;
create policy "authenticated can read order returns" on public.order_returns for select to authenticated using (true);
drop policy if exists "authenticated can insert order returns" on public.order_returns;
create policy "authenticated can insert order returns" on public.order_returns for insert to authenticated with check (true);
drop policy if exists "authenticated can read return items" on public.order_return_items;
create policy "authenticated can read return items" on public.order_return_items for select to authenticated using (true);
drop policy if exists "authenticated can insert return items" on public.order_return_items;
create policy "authenticated can insert return items" on public.order_return_items for insert to authenticated with check (true);

create or replace function public.process_order_return(
  p_order_id bigint,
  p_return_type text,
  p_reason text,
  p_notes text,
  p_refund_amount numeric,
  p_refund_method text,
  p_items jsonb
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_return_id bigint;
  v_item jsonb;
  v_source_type text;
  v_source_id text;
  v_name text;
  v_qty numeric;
  v_sold numeric;
  v_condition text;
  v_restored boolean;
  v_current numeric;
  v_user uuid := auth.uid();
begin
  if not exists (select 1 from public.orders where id = p_order_id) then
    raise exception 'الطلب غير موجود';
  end if;
  if coalesce(trim(p_reason),'') = '' then
    raise exception 'سبب الإرجاع مطلوب';
  end if;
  if p_return_type not in ('full','partial') then
    raise exception 'نوع الإرجاع غير صحيح';
  end if;
  if coalesce(p_refund_amount,0) < 0 then
    raise exception 'المبلغ المسترجع غير صحيح';
  end if;

  insert into public.order_returns(order_id,return_type,reason,notes,refund_amount,refund_method,created_by)
  values(p_order_id,p_return_type,trim(p_reason),nullif(trim(coalesce(p_notes,'')),''),coalesce(p_refund_amount,0),coalesce(nullif(trim(p_refund_method),''),'cash'),v_user)
  returning id into v_return_id;

  for v_item in select value from jsonb_array_elements(coalesce(p_items,'[]'::jsonb))
  loop
    v_source_type := v_item->>'sourceType';
    v_source_id := nullif(v_item->>'sourceId','');
    v_name := coalesce(nullif(v_item->>'name',''),'عنصر');
    v_qty := coalesce((v_item->>'returnQuantity')::numeric,0);
    v_sold := coalesce((v_item->>'soldQuantity')::numeric,0);
    v_condition := v_item->>'condition';
    v_restored := false;

    if v_source_type not in ('product_detail','usage_tier','external') then raise exception 'مصدر عنصر الإرجاع غير صحيح'; end if;
    if v_condition not in ('good','damaged') then raise exception 'حالة عنصر الإرجاع غير صحيحة'; end if;
    if v_qty <= 0 or v_qty > v_sold then raise exception 'كمية الإرجاع غير صحيحة للعنصر %', v_name; end if;

    if v_condition = 'good' and v_source_type = 'product_detail' and v_source_id is not null then
      select stock into v_current from public.product_details where id = v_source_id::bigint for update;
      if not found then raise exception 'مادة المخزون غير موجودة: %', v_name; end if;
      update public.product_details set stock = coalesce(v_current,0) + v_qty where id = v_source_id::bigint;
      v_restored := true;
    elsif v_condition = 'good' and v_source_type = 'usage_tier' and v_source_id is not null then
      select stock into v_current from public.usage_price_tiers where usage_price = v_source_id::numeric for update;
      if not found then raise exception 'فئة الاستخدام غير موجودة: %', v_name; end if;
      update public.usage_price_tiers set stock = coalesce(v_current,0) + v_qty where usage_price = v_source_id::numeric;
      v_restored := true;
    end if;

    insert into public.order_return_items(return_id,source_type,source_id,item_name,sold_quantity,return_quantity,item_condition,restored_to_stock)
    values(v_return_id,v_source_type,v_source_id,v_name,v_sold,v_qty,v_condition,v_restored);
  end loop;

  update public.orders
  set status = case when p_return_type = 'full' then 'returned' else 'partially_returned' end,
      delivery_status = case when p_return_type = 'full' then 'returned' else delivery_status end
  where id = p_order_id;

  if to_regclass('public.owner_notifications') is not null then
    insert into public.owner_notifications(notification_type,title,message,entity_table,entity_id,created_by)
    values('order_return','تم تسجيل مرتجع',format('تم إرجاع الطلب #%s. السبب: %s. المبلغ المسترجع: %s د.ل',p_order_id,p_reason,coalesce(p_refund_amount,0)),'orders',p_order_id::text,v_user);
  end if;

  return v_return_id;
end;
$$;

grant execute on function public.process_order_return(bigint,text,text,text,numeric,text,jsonb) to authenticated;
